### ISSUE TITLE
Request: npm package

### ISSUE THREAD

**Issue by rjschmitt** [abecks/react-jsonschema-form-plugin-bs4#1]
Hi,

I really appreciate, what you coded with this plugin. 
Would you mind to publish this package as npm-package?

Kind regards

**Comment by dechamp** [comment]
I second this, will you please add this?

**Comment by abecks** [comment]
Unfortunately this package was never completed and does not support all BS4 components yet. Feel free to fork this repo and finish the work. I can't support this as I no longer use react-jsonschema-form.

**Comment by dechamp** [comment]
Curious as to what you use now. 


DeChamp

**Comment by abecks** [comment]
I built my own form components and use ajv for validation
